import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import { Header } from '../_componments/Header';
import { Footer } from '../_componments/Footer';
import { ToastContainer } from '../_utils/Toast';
import './globals.css';
import { Banner } from '../_componments/BannerList';
import { usePathname } from 'next/navigation';
import { AuthProvider } from '@/_componments/AuthProvider';
import { SearchProvider } from '../_context/SearchContext';
const inter = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'FreshSolder',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <AuthProvider>
      <SearchProvider>
        <body className={inter.className}>
          <Header />
          <div className='h-[73px]'></div>
          {children}
          <Banner />
          <Footer />
          <ToastContainer />
        </body>
      </SearchProvider>
      </AuthProvider>
    </html>
  );
}
