import type { Metadata } from "next";
import { Noto_Sans, Ubuntu, Outfit } from "next/font/google";
import {Header} from "../_componments/Header";
import { Footer } from '../_componments/Footer';
import { ToastContainer } from "../_utils/Toast";
import "./globals.css";
import { BannerType } from '../types';
import {useState, useEffect} from "react";
import { Banner } from "../_componments/BannerList";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <div className='h-20'></div>
        {children}
        <Banner />
        <Footer />
        <ToastContainer/>
      </body>
    </html>
  );
}
